export const USER_REGISTRATION_START = "USER_REGISTRATION_START"
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS"
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL"

export const USER_LOGIN_START = "USER_LOGIN_START"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const BLOG_POST_START = "BLOG_POST_START"
export const BLOG_POST_SUCCESS = "BLOG_POST_SUCCESS"
export const BLOG_POST_FAIL = "BLOG_POST_FAIL"

export const GET_BLOGS_START = "GET_BLOGS_START"
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS"
export const GET_BLOGS_FAIL = "GET_BLOGS_FAIL"

export const POST_COMMENT_START = "POST_COMMENT_START"
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL"

export const USER_LOGOUT = "USER_LOGOUT"

export const MODAL_HANDLER = "MODAL_HANDLER"
